[package]
name = "axomai_engine"
version = "0.8.0"
edition = "2021"
authors = ["Samarjit Kashyap <samarjitkashyp@gmail.com>"]
description = "High-performance Rust Browser Engine for Axomai Browser"

[lib]
name = "axomai_engine"
crate-type = ["cdylib", "rlib"]

[dependencies]
ureq = { version = "2.9", features = ["tls"] }
html-escape = "0.2"
v8 = "152.2.0"

[features]
default = []
