# -*- coding: utf-8 -*-
"""Words of the landing page in English, Assamese, Hindi and Bengali.
The Assamese, Hindi and Bengali texts were written without a native reviewer; please have them read before relying on them."""

SITE = 'https://axomai-browser.aiaxom.co.in'
GITHUB = 'https://github.com/Samarjitkashyp/axomai-browser'
LANGS = [('en', 'English', '/'), ('as', 'অসমীয়া', '/as/')]
# The Assamese page is published for readers but kept out of search engines until a native speaker has reviewed it.
REVIEWED = {'en': True, 'as': False}
HTML_LANG = {'en': 'en', 'as': 'as'}
OG_LOCALE = {'en': 'en_IN', 'as': 'as_IN'}

EN = dict(
    title='Axomai Browser – Free AI Browser for Windows, Made in Assam',
    desc='Axomai Browser is a free Windows browser with built-in AI chat, Assamese, Hindi and Bengali menus, ad blocking and Assam-inspired themes. Download v{version}.',
    nav=[('#ai', 'AI chat'), ('#assam', 'Made in Assam'), ('#privacy', 'Privacy'), ('#more', 'Features'), ('#faq', 'FAQ')],
    eyebrow='Free · Made in Assam · Windows 10 &amp; 11',
    h1='Axomai Browser: the free <em>AI browser</em> made in Assam',
    lead='Browse the web with artificial intelligence built in. Ask Axom AI about the page you are reading, in Assamese, Hindi, Bengali or English, and keep your browsing private.',
    cta='Download for Windows', cta_short='Download', nowin_h='This is a Windows browser', nowin_p='Axomai Browser installs on Windows 10 and 11 PCs. Open this page on your Windows computer, or send yourself the link.', nowin_btn='Share this link', cta_meta='v{version} · {size} MB · 64-bit', secondary='See what is inside',
    fine='Free. Windows 10 or 11 (64-bit). Windows may show a blue “Windows protected your PC” screen because the installer is not code-signed yet: choose <b>More info</b>, then <b>Run anyway</b>. SHA-256: <code id="sha">{sha}</code>',
    shot_url='Page alpha — Assam tea garden notes', shot_title='Tea in Assam', shot_sub='Axomai Browser is showing a page about Assam tea.',
    chat=[('u', 'What is this page about?'), ('a', 'It is a short note about tea gardens in Assam and how tea is grown there. Want me to list the key points?'), ('u', 'Yes, please'), ('a', 'Sure. 1) Tea grows best in the warm, wet Brahmaputra valley. 2) The leaves are plucked by hand. 3) Axom AI can answer in Assamese, Hindi, Bengali or English.')],
    strip=[('Free', 'to download and use'), ('4 languages', 'Assamese · Hindi · Bengali · English'), ('No sign-in', 'no account needed'), ('Verified updates', 'checked against a published checksum')],
    def_kicker='In one minute', def_h='What is Axomai Browser?',
    def_p='<strong>Axomai Browser is a free web browser for Windows, made in Assam, with an AI assistant (Axom AI) built in.</strong> The assistant can answer questions about the page you are reading. The browser has menus in Assamese, Hindi, Bengali and English, blocks ads and trackers, and comes with five themes inspired by Assam. It uses the same Microsoft Edge WebView2 (Chromium) engine as other modern browsers, so websites work the way you expect.',
    facts_h='Axomai Browser at a glance',
    facts=[('Name', 'Axomai Browser (also written Axom AI Browser)'), ('Made by', 'Samarjit Kashyap, Assam, India'), ('Platform', 'Windows 10 and Windows 11, 64-bit'), ('Price', 'Free (daily fair-use limit on AI chat)'), ('Languages', 'Assamese, Hindi, Bengali, English'), ('Engine', 'Microsoft Edge WebView2 (Chromium)'), ('Latest version', '{version}'), ('Download size', '{size} MB'), ('Source code', 'github.com/Samarjitkashyp/axomai-browser')],
    features=[
        dict(id='ai', kicker='Artificial intelligence', h='Ask AI about the page you are reading', p='Axom AI lives in the browser. Open the AI button, ask a question, and the answer streams in. Leave “Use this page to answer” on and it reads the page with you.',
             bullets=['Summarize, explain in simple words, or pull out the key points', 'Understands and answers in Assamese, Hindi, Bengali and English', 'Powered by OpenAI models through Axomai’s own server, so there is no key to paste', 'Fair-use limit of 30 AI messages per person per day; chats are not saved'],
             vis=[('✨', 'Summarize this page'), ('\U0001F4D6', 'Explain this in simple words'), ('\U0001F310', 'Answer in Assamese'), ('\U0001F512', 'Chats are not saved')]),
        dict(id='assam', kicker='Made in Assam', h='A browser that speaks your language', p='Menus, settings and built-in pages come in Assamese, Hindi, Bengali and English. The New Tab page shows headlines from Assamese and North-East newspapers with photos, plus the weather for 35 towns and cities.',
             bullets=['Heritage themes: Assam Tea Garden, Kaziranga Mist, Brahmaputra Azure, Gamosa Crimson and Obsidian Dark Glass', 'Translate any page into Assamese, Hindi, Bengali and nine more languages', 'Read pages aloud with the Windows voice', 'Voice commands such as “new tab” and “go back”'],
             vis=[('\U0001F5DE️', 'Assam headlines with photos'), ('☀️', 'Weather for Jorhat, Guwahati, Dibrugarh…'), ('\U0001F3A8', '5 heritage themes'), ('\U0001F310', 'Assamese · हिन्दी · বাংলা')]),
        dict(id='privacy', kicker='Private by default', h='Your browsing stays yours', p='Axomai blocks ads and trackers, upgrades sites to HTTPS, sends the Global Privacy Control signal and hides cookie banners. Saved passwords are encrypted with your Windows account.',
             bullets=['Ad and tracker blocking, anti-fingerprinting and HTTPS-only mode', 'Passwords encrypted with Windows; Windows Hello can protect copying and exporting', 'Per-site permissions, zoom, mute and block in one Site settings page', 'Private windows that leave nothing behind'],
             vis=[('\U0001F6E1️', 'Ads and trackers blocked'), ('\U0001F510', 'HTTPS-only mode'), ('\U0001F511', 'Passwords encrypted with Windows'), ('\U0001F575️', 'Private windows')]),
        dict(id='more', kicker='Do more', h='Everything you need to get more done', p='Tab groups, tab search, split view, a reading list, sticky notes on pages and saved sessions keep research organised.',
             bullets=['Picture-in-picture video, a screenshot editor with arrows, highlights and blur', 'Dark mode for websites, clean printouts and a YouTube ad skipper', 'Search shortcuts: type @yt, @wiki or @maps in the address bar', 'Chrome extensions (load unpacked), bookmark and password import', 'Sync between your PCs through your own folder, end-to-end encrypted'],
             vis=[('\U0001F5C2️', 'Tab groups and tab search'), ('\U0001F4DD', 'Notes on any page'), ('\U0001F4D6', 'Reading list'), ('\U0001F9E9', 'Chrome extensions')]),
    ],
    themes_h='Five themes inspired by Assam', themes_p='Pick the look that feels like home. Every page, menu and popup follows the theme.',
    themes=[('Assam Tea Garden', '#059669,#f59e0b'), ('Kaziranga Mist', '#15803d,#d97706'), ('Brahmaputra Azure', '#0284c7,#06b6d4'), ('Gamosa Crimson', '#dc2626,#fb923c'), ('Obsidian Dark Glass', '#0b1220,#10b981')],
    gallery_h='Assam, in pictures', gallery_note='Illustrative images.',
    gallery=[('tea-garden.jpg', 'Green tea gardens of Assam at sunrise', 'Tea gardens at sunrise'), ('kaziranga.jpg', 'Tea hills and forest with mountains in the distance, Assam', 'Hills, forests and rivers'), ('bihu.jpg', 'Dancers in mekhela chador performing at a Bihu festival stage', 'Bihu, the festival of Assam'), ('rhino.jpg', 'One-horned rhinoceros in tall grass, Kaziranga', 'Kaziranga’s one-horned rhino')],
    install_h='Install Axomai Browser in three steps',
    steps=[('Download', 'Choose <b>Download for Windows</b>. The file is about {size} MB.'), ('Run the installer', 'Open <b>Axomai-Setup-{version}.exe</b>. If Windows shows a blue screen, choose <b>More info</b> and then <b>Run anyway</b>. No administrator rights are needed.'), ('Start browsing', 'Find <b>Axomai Browser</b> in the Start menu or on the desktop. Pick your language and theme in Settings.')],
    req_h='Good to know',
    req=['Windows 10 or 11, 64-bit. Mac, Linux and Android are not available yet.', 'The AI chat needs an internet connection. What you type, and the page text if you leave that on, goes to OpenAI through Axomai’s server.', 'The installer is not code-signed yet. You can compare the SHA-256 shown above with the downloaded file.'],
    faq_h='Frequently asked questions',
    faq=[
        ('What is Axomai Browser?', 'Axomai Browser is a free Windows web browser made in Assam. It has a built-in AI assistant called Axom AI that can answer questions about the page you are reading, menus in Assamese, Hindi, Bengali and English, ad and tracker blocking, and five Assam-inspired themes.'),
        ('Is Axomai Browser free?', 'Yes. It is free to download and use. The AI chat has a fair-use limit of 30 messages per person per day so that it can stay free.'),
        ('Which AI does Axom AI use?', 'Axom AI uses OpenAI’s GPT models (currently gpt-5.4-mini). The browser talks to Axomai’s own server, which holds the key, so you never need to paste an API key and the browser cannot expose one.'),
        ('Does Axomai Browser support Assamese?', 'Yes. Menus, settings and built-in pages are available in Assamese, Hindi, Bengali and English. Axom AI replies in the language you write in, and you can translate any page into Assamese.'),
        ('Which versions of Windows does it run on?', 'Windows 10 and Windows 11, 64-bit. It uses Microsoft Edge WebView2, which is included in Windows 11 and in up-to-date Windows 10.'),
        ('Why does Windows show a warning when I run the installer?', 'The installer is not code-signed yet, so Windows SmartScreen shows “Windows protected your PC”. Choose More info, then Run anyway. You can check the download against the SHA-256 shown on this page, and the source code is public on GitHub.'),
        ('Is my browsing data private?', 'Your history, bookmarks and settings stay on your computer. Passwords are encrypted with your Windows account. When you use the AI chat, your question (and the page text if “Use this page” is on) is sent to OpenAI through Axomai’s server; Axomai does not save the chats.'),
        ('Can I use Chrome extensions?', 'Yes. Open the Extensions page and choose Load unpacked to add an unpacked Chrome extension. Extensions that depend on Chrome’s own online services will not work.'),
        ('Can I move my bookmarks and passwords from Chrome?', 'Yes. You can import Chrome bookmarks (from Chrome itself or an exported file) and import passwords from a CSV file.'),
        ('Does it sync between my computers?', 'Yes, without an Axomai account. Choose a folder that OneDrive, Google Drive or Dropbox shares between your PCs and a passphrase; Axomai keeps one end-to-end encrypted file there.'),
        ('How does Axomai Browser update?', 'It checks once a day and asks before updating. The installer is downloaded only if its SHA-256 matches the checksum published with the release.'),
        ('Is there a version for Mac, Linux or Android?', 'Not yet. Axomai Browser is for Windows 10 and 11 for now.'),
        ('How is it different from Chrome or Edge?', 'It runs on the same Chromium-based engine as Microsoft Edge, so websites work the same way. The differences are the built-in AI chat, the Assamese-first interface and news, the Assam-inspired themes and that no sign-in is needed.'),
    ],
    final_h='Try the free AI browser made in Assam', final_p='Download Axomai Browser for Windows and ask Axom AI about the next page you read.',
    footer_note='Axomai Browser is made by Samarjit Kashyap in Assam, India.', footer_links=[('Download', '/downloads/Axomai-Setup-{version}.exe'), ('Source code', GITHUB), ('FAQ', '#faq')],
    howto_name='How to install Axomai Browser on Windows',
)

AS = dict(
    title='আক্সমাই ব্ৰাউজাৰ – অসমৰ বাবে নিঃশুল্ক AI ব্ৰাউজাৰ (Axomai Browser)',
    desc='Axomai Browser হৈছে Windows-ৰ বাবে নিঃশুল্ক ব্ৰাউজাৰ। ইয়াত AI চ্ট, অসমীয়া, হিন্দী, বাংলা মেনু, বি駉্ঞাপন ব্লক আৰু অসমৰ থিম আছে। v{version} ডাউনলোড কৰক।',
    nav=[('#ai', 'AI চ্ট'), ('#assam', 'অসমত বনাৱা'), ('#privacy', 'গোপনীয়তা'), ('#more', 'বৈশিষ্ট্য'), ('#faq', 'প্ৰায়ে সোধা প্ৰশ্ন')],
    eyebrow='নিঃশুল্ক · অসমত বনাৱা · Windows 10 &amp; 11',
    h1='আক্সমাই ব্ৰাউজাৰ: অসমত বনাৱা নিঃশুল্ক <em>AI ব্ৰাউজাৰ</em>',
    lead='কৃত্ৰিম বুদ্ধিমত্তা (AI) সহ ইন্টাৰনেট ব্ৰাউজ কৰক। আপুনি প্ৰরিহোঁতে পৃষ্ঠাটোৰ বাবে Axom AI-ক অসমীয়া, হিন্দী, বাংলা বা ইংৰাজীত সোধক, আৰু আপোনাৰ ব্ৰাউজিং গোপনীয় ৰাখক।',
    cta='Windows-ৰ বাবে ডাউনলোড কৰক', cta_short='\u09a1\u09be\u0989\u09a8\u09b2\u09cb\u09a1', nowin_h='\u098f\u0987\u099f\u09cb Windows-\u09f0 \u09ac\u09cd\u09f0\u09be\u0989\u099c\u09be\u09f0', nowin_p='Axomai Browser Windows 10 \u0986\u09f0\u09c1 11 PC-\u09a4 \u0987\u09a8\u09b7\u09cd\u099f\u09b2 \u09b9\u09af\u09bc\u0964 \u0986\u09aa\u09cb\u09a8\u09be\u09f0 Windows \u0995\u09ae\u09cd\u09aa\u09bf\u0989\u099f\u09be\u09f0\u09a4 \u098f\u0987 \u09aa\u09c3\u09b7\u09cd\u09a0\u09be \u0996\u09cb\u09b2\u0995, \u09ac\u09be \u09b2\u09bf\u0982\u0995\u099f\u09cb \u09a8\u09bf\u099c\u0995\u09c7 \u09aa\u09a0\u09be\u0993\u0995\u0964', nowin_btn='\u09b2\u09bf\u0982\u0995 \u09b6\u09cd\u09ac\u09c7\u09af\u09bc\u09be\u09f0 \u0995\u09f0\u0995', cta_meta='v{version} · {size} MB · 64-bit', secondary='ভিতৰত কি আছে চাওক',
    fine='নিঃশুল্ক। Windows 10 বা 11 (64-bit)। ইনষ্টলাৰটো এতিয়ালৈকে code-signed নহয়, সেইবাবে Windows-ত নীলা পর্দা আহিলে <b>More info</b> তাৰ পিছত <b>Run anyway</b> চাপক। SHA-256: <code id="sha">{sha}</code>',
    shot_url='Page alpha — Assam tea garden notes', shot_title='অসমৰ চা', shot_sub='Axomai Browser-ত অসমৰ চাৰ পৃষ্ঠা দেখুৱাইছে।',
    chat=[('u', 'এই পৃষ্ঠাটো কিৰ বিষয়ে?'), ('a', 'এইটো অসমৰ চা-বগিচা আৰু চাৰ খেতিৰ বিষয়ে এখন সংক্ষিপ্ত টোকা। প্ৰধান কথাবোৰ তালিকা পাবনে?')],
    strip=[('নিঃশুল্ক', 'ডাউনলোড আৰু ব্যৱহাৰ'), ('৪টা ভাষা', 'অসমীয়া · হিন্দী · বাংলা · English'), ('সাইন-ইন লাগিব নলগে', 'কোনো একাউন্ট লাগিব নলগে'), ('নিৰাপদ আপডেট', 'প্ৰকাশিত checksum-র সৈতে সমান')],
    def_kicker='এক মিনিটত', def_h='Axomai Browser কি?',
    def_p='<strong>Axomai Browser হৈছে Windows-ৰ বাবে অসমত বনাৱা এখন নিঃশুল্ক ব্ৰাউজাৰ, যিত AI সহায়ক (Axom AI) আছে।</strong> ইয়াৰ সহায়ত আপুনি পরা পৃষ্ঠাৰ বাবে প্ৰশ্ন কৰিব পাৰে। ইয়াত অসমীয়া, হিন্দী, বাংলা আৰু ইংৰাজী মেনু, বি駉্ঞাপন আৰু ট্ৰেকাৰ ব্লক আৰু অসমৰ প্ৰেৰণাৰ পাঁচটা থিম আছে।',
    facts_h='এক ঝাঁকিত Axomai Browser',
    facts=[('নাম', 'Axomai Browser'), ('বনাৱনিকাৰী', 'Samarjit Kashyap, অসম, ভাৰত'), ('প্লেটফৰ্ম', 'Windows 10 আৰু 11, 64-bit'), ('মুল্য', 'নিঃশুল্ক'), ('ভাষা', 'অসমীয়া, হিন্দী, বাংলা, English'), ('সংস্কৰণ', '{version}'), ('আকাৰ', '{size} MB'), ('সোর্ছ কোড', 'github.com/Samarjitkashyp/axomai-browser')],
    features=[
        dict(id='ai', kicker='কৃত্ৰিম বুদ্ধিমত্তা', h='আপুনি পরা পৃষ্ঠাৰ বাবে AI-ক সোধক', p='Axom AI ব্ৰাউজাৰতে আছে। AI বাটন চাপি প্ৰশ্ন কৰক, উত্তৰ একেবাৰে আহি থকাৰ দোঁতে লিখা হৈ থাকিব।',
             bullets=['সংক্ষিপ্ত বা সহজ ভাষাত ব্যাখ্যা', 'অসমীয়া, হিন্দী, বাংলা আৰু English-ত উত্তৰ', 'আপোনাৰ API key লাগিব নলগে', 'প্ৰতিদিনে ৩০টা বাৰ্তাৰ সীমা; চ্ট সংৰক্ষণ নহয়'],
             vis=[('✨', 'পৃষ্ঠাটোৰ সাৰাংশ'), ('\U0001F4D6', 'সহজ ভাষাত ব্যাখ্যা'), ('\U0001F310', 'অসমীয়াত উত্তৰ'), ('\U0001F512', 'চ্ট সংৰক্ষণ নহয়')]),
        dict(id='assam', kicker='অসমত বনাৱা', h='আপোনাৰ ভাষাত কথা কোৱা ব্ৰাউজাৰ', p='মেনু, ছেটিং আৰু ভিতৰৰ পৃষ্ঠা অসমীয়া, হিন্দী, বাংলা আৰু English-ত আছে। New Tab-ত অসম আৰু উত্তৰ-পুৰ্বৰ সংবাদপত্ৰৰ সংবাদ, ছবি আৰু ৩৫টা শহৰৰ পৰিবেশ দেখা পাইব।',
             bullets=['অসমৰ ঐতিহ্যৰ পাঁচটা থিম: চা বগিচা, কাজিৰঙ্গা, ব্ৰহ্মপুত্ৰ, গামছা, অবসিডিয়ান', 'যিকোনো পৃষ্ঠা অসমীয়া, হিন্দী, বাংলা আৰু আৰু ৮টা ভাষাত অনুবাদ', 'পৃষ্ঠা উচ্চ স্বৰে পৰা শুনিবলৈ', 'ভৰিস কমান্ড'],
             vis=[('\U0001F5DE️', 'ছবিসহ অসমৰ সংবাদ'), ('☀️', 'জোৰহাট, গুৱাহাটী, ডিব্ৰুগড়ৰ পৰিবেশ'), ('\U0001F3A8', '৫টা থিম'), ('\U0001F310', 'অসমীয়া · হিন্দী · বাংলা')]),
        dict(id='privacy', kicker='স্বভাবতে গোপনীয়', h='আপোনাৰ ব্ৰাউজিং আপোনাৰেই', p='Axomai বি駉্ঞাপন আৰু ট্ৰেকাৰ ব্লক কৰে, ছাইট HTTPS-ত লৈ যায় আৰু সংৰক্ষিত পাছওৱাৰ্ড Windows একাউন্টৰে এনক্ৰিপ্ট কৰে।',
             bullets=['বি駉্ঞাপন আৰু ট্ৰেকাৰ ব্লক, HTTPS-only মোড', 'Windows Hello ৰে পাছওৱাৰ্ড কপি আৰু ৰপ্তানিৰ সুৰক্ষা', 'ছাইটৰ অনুমতি, জুম, মিউট আৰু ব্লক এখন পৃষ্ঠাত', 'প্ৰাইভেট উইন্ডো'],
             vis=[('\U0001F6E1️', 'বি駉্ঞাপন আৰু ট্ৰেকাৰ ব্লক'), ('\U0001F510', 'HTTPS-only'), ('\U0001F511', 'এনক্ৰিপ্টেড পাছওৱাৰ্ড'), ('\U0001F575️', 'প্ৰাইভেট উইন্ডো')]),
        dict(id='more', kicker='আৰু বেছি কাম', h='আৰু বেছি কাম কৰিবলৈ সকলো সামগ্ৰী', p='টেব গ্ৰুপ, টেব সাৰ্চ, স্প্লিট ভিউ, রিডিং লিষ্ট, পৃষ্ঠাত নোট আৰু সংৰক্ষিত ছেছন।',
             bullets=['ছবিৰ সম্পাদক, পিকচাৰ-ইন-পিকচাৰ, ছাইটৰ ডাৰ্ক মোড', 'Chrome extension, বুকমাৰ্ক আৰু পাছওৱাৰ্ড আমদানি', 'আপোনাৰ নিজৰ ফোল্ডাৰৰ জৰিয়তে পিসিৰ মাজত ছিংক'],
             vis=[('\U0001F5C2️', 'টেব গ্ৰুপ আৰু সাৰ্চ'), ('\U0001F4DD', 'পৃষ্ঠাত নোট'), ('\U0001F4D6', 'রিডিং লিষ্ট'), ('\U0001F9E9', 'Chrome extension')]),
    ],
    themes_h='অসমৰ প্ৰেৰণাৰ পাঁচটা থিম', themes_p='আপোনাৰ ভাল লগা থিম বাছি লওক।',
    themes=[('অসম চা বগিচা', '#059669,#f59e0b'), ('কাজিৰঙ্গা মিষ্ট', '#15803d,#d97706'), ('ব্ৰহ্মপুত্ৰ আজুৰ', '#0284c7,#06b6d4'), ('গামছা ক্ৰিমছন', '#dc2626,#fb923c'), ('অবসিডিয়ান ডাৰ্ক', '#0b1220,#10b981')],
    gallery_h='ছবিত অসম', gallery_note='উদাহৰণস্বৰূপ ছবি।',
    gallery=[('tea-garden.jpg', 'Green tea gardens of Assam at sunrise', 'ভোৰৰ চা বগিচা'), ('kaziranga.jpg', 'Tea hills and forest with mountains in the distance, Assam', 'পাহাৰ, বন আৰু নদী'), ('bihu.jpg', 'Dancers in mekhela chador performing at a Bihu festival stage', 'বিহু, অসমৰ উৎসব'), ('rhino.jpg', 'One-horned rhinoceros in tall grass, Kaziranga', 'কাজিৰঙ্গাৰ গৈঁডা')],
    install_h='তিনিখাপত Axomai Browser ইনষ্টল কৰক',
    steps=[('ডাউনলোড', '<b>Windows-ৰ বাবে ডাউনলোড কৰক</b> চাপক। ফাইলটো প্ৰায় {size} MB।'), ('ইনষ্টলাৰ চলাওক', '<b>Axomai-Setup-{version}.exe</b> খোলক। Windows-ত নীলা পৰ্দা আহিলে <b>More info</b> তাৰ পিছত <b>Run anyway</b> চাপক। administrator লাগিব নলগে।'), ('ব্ৰাউজিং আৰম্ভ কৰক', 'Start menu বা desktop-ত <b>Axomai Browser</b> পাইব। Settings-ত ভাষা আৰু থিম বাছি লওক।')],
    req_h='জানি ৰাখক',
    req=['Windows 10 বা 11, 64-bit। Mac, Linux আৰু Android এতিয়ালৈ নাই।', 'AI চ্টৰ বাবে ইন্টাৰনেট লাগে। আপুনি যেতিয়া লিখে (আৰু পৃষ্ঠাৰ পাঠ থকা অৱস্থাত), সেইটো Axomai-ৰ সাৰ্ভাৰৰ জৰিয়তে OpenAI-লৈ যায়।', 'ইনষ্টলাৰটো এতিয়ালৈ code-signed নহয়।'],
    faq_h='প্ৰায়ে সোধা প্ৰশ্ন',
    faq=[
        ('Axomai Browser কি?', 'Axomai Browser হৈছে অসমত বনাৱা আৰু Windows-ৰ বাবে নিঃশুল্ক ব্ৰাউজাৰ। ইয়াত Axom AI নামৰ AI সহায়ক আছে যিয়ে আপুনি পরা পৃষ্ঠাৰ বাবে প্ৰশ্নৰ উত্তৰ দিব পাৰে। ইয়াত অসমীয়া, হিন্দী, বাংলা আৰু English মেনু।'),
        ('Axomai Browser নিঃশুল্কনে?', 'হয়, ডাউনলোড আৰু ব্যৱহাৰ নিঃশুল্ক। AI চ্টত প্ৰতিজনৰ বাবে প্ৰতিদিনে ৩০টা বাৰ্তাৰ সীমা আছে।'),
        ('Axom AI-যি কোন AI ব্যৱহাৰ কৰে?', 'Axom AI-যি OpenAI-ৰ GPT মডেল (বৰ্তমান gpt-5.4-mini) ব্যৱহাৰ কৰে। ব্ৰাউজাৰে Axomai-ৰ নিজৰ সাৰ্ভাৰৰ সৈতে কথা পাতে, তাতেই key আছে।'),
        ('ইয়াত অসমীয়া আছেনে?', 'আছে। মেনু, ছেটিং আৰু ভিতৰৰ পৃষ্ঠা অসমীয়া, হিন্দী, বাংলা আৰু English-ত আছে। Axom AI-যি আপুনি যি ভাষাত লিখে সেই ভাষাত উত্তৰ দিয়ে।'),
        ('ইয়াৰ বাবে কোন Windows লাগে?', 'Windows 10 আৰু Windows 11, 64-bit।'),
        ('আপোনাৰ ব্ৰাউজিং ডেটা গোপনীয়নে?', 'আপোনাৰ ইতিহাস, বুকমাৰ্ব আৰু ছেটিং আপোনাৰ কম্পিউটাৰতেই থাকে। AI চ্ট ব্যৱহাৰ কৰিলে আপোনাৰ প্ৰশ্ন OpenAI-লৈ যায়; Axomai-যি চ্ট সংৰক্ষণ কৰে নাই।'),
        ('Chrome extension ব্যৱহাৰ কৰিব পাৰিনে?', 'পাৰি। Extensions পৃষ্ঠাত Load unpacked বাছি unpacked Chrome extension যোগ কৰক।'),
    ],
    final_h='অসমত বনাৱা নিঃশুল্ক AI ব্ৰাউজাৰ ব্যৱহাৰ কৰক', final_p='Windows-ৰ বাবে Axomai Browser ডাউনলোড কৰক আৰু আপোনাৰ পৰৱৰ্তী পৃষ্ঠাৰ বাবে Axom AI-ক সোধক।',
    footer_note='Axomai Browser Samarjit Kashyap-র দ্ৱাৰা অসম, ভাৰতত বনাৱা।', footer_links=[('ডাউনলোড', '/downloads/Axomai-Setup-{version}.exe'), ('Source code', GITHUB), ('FAQ', '#faq')],
    howto_name='Windows-ত Axomai Browser কেনেকৈ ইনষ্টল কৰিব',
)
